name: Deployment Status

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  pre-deployment:
    runs-on: ubuntu-latest
    outputs:
      issue_number: ${{ steps.create_issue.outputs.issue_number }}
      previous_commit: ${{ steps.capture.outputs.previous_commit }}
      commit_sha: ${{ steps.capture.outputs.commit_sha }}
      package_version: ${{ steps.capture.outputs.package_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Run tests
        run: npm test --if-present
      - name: Capture commit and version
        id: capture
        run: |
          PREVIOUS_COMMIT=$(git rev-parse HEAD^)
          COMMIT_SHA_HEAD=${GITHUB_SHA}
          PKG_VERSION=$(node -p "require('./package.json').version" || echo "")
          echo "previous_commit=$PREVIOUS_COMMIT" >> $GITHUB_OUTPUT
          echo "commit_sha=$COMMIT_SHA_HEAD" >> $GITHUB_OUTPUT
          echo "package_version=$PKG_VERSION" >> $GITHUB_OUTPUT
      - name: Create deployment tracking issue
        id: create_issue
        uses: actions/github-script@v6
        with:
          script: |
            const commitSha = '${{ steps.capture.outputs.commit_sha }}';
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue = await github.issues.create({ owner, repo, title: `Deployment Tracking - ${commitSha}` });
            const number = issue.data.number;
            await github.issues.addLabels({ owner, repo, issue_number: number, labels: ['deployment','in-progress'] });
            core.setOutput('issue_number', number);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Post pre-deployment comment
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = '${{ steps.create_issue.outputs.issue_number }}';
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            await github.issues.createComment({ owner, repo, issue_number, body: 'Pre-deployment checks completed' });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  rollback-preparation:
    needs: pre-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Prepare rollback artifacts
        id: rollback
        run: |
          COMMIT_SHA='${{ needs.pre-deployment.outputs.commit_sha }}'
          PREV_COMMIT='${{ needs.pre-deployment.outputs.previous_commit }}'
          VERSION='${{ needs.pre-deployment.outputs.package_version }}'
          mkdir -p artifacts/rollback
          mkdir -p artifacts/rollback/backup
          # Rollback script
          cat > artifacts/rollback/rollback.sh <<'EOS'
#!/usr/bin/env bash
set -euo pipefail
PREVIOUS=${PREV_COMMIT}
CURRENT=${COMMIT_SHA}

git fetch --all
git reset --hard "$PREVIOUS"
EOS
          chmod +x artifacts/rollback/rollback.sh
          # Backups
          cp package.json artifacts/rollback/backup/ 2>/dev/null || true
          cp package-lock.json artifacts/rollback/backup/ 2>/dev/null || true
          if [ -f .env.example ]; then
            cp .env.example artifacts/rollback/backup/.env.example
          fi
          if [ -d environments ]; then
            cp -r environments artifacts/rollback/backup/environments
          fi
          # Dependency verification script
          cat > artifacts/rollback/verify-deps.sh <<'EOS'
#!/usr/bin/env bash
set -euo pipefail
node -v
npm -v
EOS
          chmod +x artifacts/rollback/verify-deps.sh
          # Documentation
          cat > artifacts/rollback/README-rollback.md <<'MD'
# Rollback Plan
This document describes how to rollback a deployment manually.
MD
          # Tarball
          tar -czf rollback-package-${COMMIT_SHA}.tar.gz -C artifacts/rollback .
          sha256sum rollback-package-${COMMIT_SHA}.tar.gz > rollback-package-${COMMIT_SHA}.tar.gz.sha256
      - name: Upload rollback artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rollback-artifacts-${{ needs.pre-deployment.outputs.commit_sha }}
          path: artifacts/rollback/**
          retention-days: 30
      - name: Post rollback plan comment
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = '${{ needs.pre-deployment.outputs.issue_number }}';
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const commitSha = '${{ needs.pre-deployment.outputs.commit_sha }}';
            const previousCommit = '${{ needs.pre-deployment.outputs.previous_commit }}';
            const packageVersion = '${{ needs.pre-deployment.outputs.package_version }}';
            const artifactName = `rollback-package-${commitSha}`;
            const fs = require('fs');
            let checksum = '';
            try {
              checksum = fs.readFileSync(`rollback-package-${commitSha}.tar.gz.sha256`, 'utf8').trim().split(/\\s+/)[0];
            } catch (e) {
              checksum = '';
            }
            const body = [
              '**Title:** 🔄 Rollback Plan Ready',
              `- Previous commit: ${previousCommit}`,
              `- Current commit: ${commitSha}`,
              `- Package Version: ${packageVersion}`,
              `- Artifact: ${artifactName}`,
              '✅ ✅ ✅ ✅ ✅',
              'Quick rollback command:',
              '```bash',
              'git fetch --all',
              `git reset --hard ${previousCommit}`,
              '```',
              `Rollback script created: true`,
              `Configuration backup: true`,
              `SHA256: ${checksum}`
            ].join('\n');
            await github.issues.createComment({ owner, repo, issue_number, body });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  post-deployment:
    needs: rollback-preparation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Update deployment issue and finalize
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = '${{ needs.pre-deployment.outputs.issue_number }}';
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue = await github.issues.get({ owner, repo, issue_number });
            const currentLabels = issue.data.labels.map(l => l.name);
            const updated = Array.from(new Set(currentLabels.filter(l => l !== 'in-progress').concat(['completed'])));
            await github.issues.update({ owner, repo, issue_number, labels: updated });
            const commitSha = '${{ needs.pre-deployment.outputs.commit_sha }}';
            const artifactName = `rollback-package-${commitSha}`;
            const body = `Deployment Completed Successfully\\nArtifact: ${artifactName}`;
            await github.issues.createComment({ owner, repo, issue_number, body });
            await github.issues.update({ owner, repo, issue_number, state: 'closed' });
